app_config: test
not_in_schema: true

network:
  server:
    host: "127.0.0.1"

test:
  req_bool_val: true
  req_int_val: 176
  req_int_list_val: [12, 13, 14, 15, 16]
  req_float_val: 1.55
  req_str_val: test string
  req_enum_val: val1
